version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 30
  rebase-strategy: "disabled"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
  rebase-strategy: "disabled"
