# Must pass on the merge with the master branch
status = [
    "CI"
]

delete_merged_branches = true

# Required to drop the large HTML part from dependabot PRs and integrated into
# our PR template (.github/PULL_REQUEST_TEMPLATE.md):
cut_body_after = "<details>"
