[package]
name = "butido"
version = "0.1.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>",
           "Matthias Beyer <matthias.beyer@atos.net>",
           "Christoph Prokop <christoph.prokop@atos.net>",
          ]
edition = "2018"
license = "EPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow         = "1"
aquamarine     = "0.1.6"
ascii_table    = ">= 3.0.2"
atty           = "0.2"
chrono         = "0.4"
clap           = "3.0.0-beta.2"
clap_generate  = "3.0.0-beta.2"
colored        = "2"
config         = "0.10"
csv            = "1.1"
diesel         = { version = "1.4", features = ["postgres", "chrono", "uuid", "serde_json"] }
env_logger     = "0.8"
filters        = "0.4.0"
futures        = "0.3"
getset         = "0.1"
git2           = "0.13"
handlebars     = { version = "3", features = ["no_logging"] }
indicatif      = "0.15"
indoc          = "1"
itertools      = "0.10"
lazy_static    = "1.4"
log            = "0.4"
parse-display  = "0.4"
pom            = "3"
ptree          = "0.3"
regex          = "1"
reqwest        = { version = "0.11", features = [ "stream" ] }
resiter        = "0.4"
result-inspect = "0.1"
semver		   = { version = "0.11", features = [ "serde" ] }
serde          = "1"
serde_json     = "1"
sha1           = { version = "0.6", features = ["std"] }
sha2           = "0.9"
shiplift       = { git = "https://github.com/softprops/shiplift", rev = "03cc8c075f86f1bd9e2c4e29872a0e8b9072c7f0" }
syntect        = "4.4"
tar            = "0.4"
terminal_size  = "0.1"
tokio          = { version = "0.2", features = ["macros", "fs", "process", "io-util", "blocking"] }
typed-builder  = "0.8"
unindent       = "0.1"
url            = { version = "2", features = ["serde"] }
uuid           = { version = "0.6", features = ["serde", "v4"] }
walkdir        = "2"
which          = "4"

# Hard-code rand to 0.4.4
#
# Reason for this is this dependency chain:
# diesel -> uuid (0.6) -> rand (0.4)
# but rand 0.4.5 depends on fuchsia-cprng which has an unclear license
# rand 0.4.4 is yanked, rand 0.4.3 does not contain this dependency.
#
# We do not explicitely need this dependency, we just want to force cargo not to
# link against rand 0.4.5 because of this licensing issue.
#
# The proper solution for this would be to update "uuid" in diesel or
# to update "rand" in uuid 0.6.
#
# Upstream issue: https://github.com/rust-random/rand/issues/1071
rand = "=0.4.3"

