[package]
name = "butido"
version = "0.1.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log         = "0.3"
tracing     = "0.1"
toml        = "0.5"
serde       = "1"
config      = "0.9"
anyhow      = "1"
getset      = "0.1"
walkdir     = "2"
resiter     = "0.4"
itertools   = "0.9"
clap-v3     = "3.0.0-beta.1"
indicatif   = "0.15"
env_logger  = "0.7"
regex       = "1"
lazy_static = "1.4"
uuid        = { version = "0.8", features = ["v4"] }
pom         = "3"
futures     = "0.3"
handlebars  = "3"
filters     = "0.4.0"
indoc       = "1"
typed-builder = "0.7"
tar         = "0.4"
diesel      = { version = "1.4", features = ["postgres", "chrono", "uuid"] }
which       = "4"
ascii_table = "3"
terminal_size = "0.1"
atty        = "0.2"
csv         = "1.1"
chrono      = "0.4"
git2	    = "0.13"

url      = { version = "2", features = ["serde"] }
tokio    = { version = "0.2", features = ["full"] }
shiplift = { git = "https://github.com/softprops/shiplift", branch = "master" }


[dev-dependencies]
indoc = "1"
