name              = "pkgA"
version           = "1.0.0"

[dependencies]
runtime = [ "pkgB =1.0.0" ]

[source]
url  = "http://somerandomthi.ng/foo/bar.tar.gz"
hash.type = "sha1"
hash.hash = "23465"

[phases]
# overwrites
install.script = '''
    ls /inputs
    [[ -e /inputs/pkgB-1.0.0.txt ]] || {
        echo "Not found: pkgB-1.0.0"
        exit 1
    }
    echo Overridden install phase in package pkgA

    mkdir -p /outputs
    touch /outputs/pkgA-1.0.0.txt
    ls /outputs
'''

