name              = "pkgA"
version           = "1.0.0"

[dependencies]
runtime = [ "pkgB =1.0.0" ]

[source]
url  = "http://somerandomthi.ng/foo/bar.tar.gz"
hash.type = "sha1"
hash.hash = "23465"

# overwrites
phases.install.script = '''
    echo Overridden install phase in package pkgA
'''

