name              = "j"
version           = "10"

[sources.src]
url       = "http://localhost:8180/j-10.source"
hash.hash = "96ef992ccecfcef89a6a964af8a83b88a1351129"

[phases]
build.script = '''
    echo "Building {{name}} in version {{version}}"
'''
