name              = "c"
version           = "3"

[phases]
package.script = '''
    mkdir /outputs
    echo "#BUTIDO:PHASE:package"
    echo "#BUTIDO:PROGRESS:90"

    touch /outputs/c-3.pkg

    echo "#BUTIDO:PROGRESS:100"
    echo "#BUTIDO:STATE:OK:finished"
'''
