version           = "1"
version_is_semver = false

# no patches by default
patches = []

[source]
url       = "https://github.com/user/repo/archive/sources.tar.gz"
hash.type = "sha1"
hash.hash = "5e8bcaa3c758f84f01935a914e2bbf01309462ae"

[dependencies]
system          = []
system_runtime  = []
build           = []
runtime         = []

# Root description of phases
# can be overridden as well
[phases]

unpack.script = '''
    mkdir /build
    echo "#BUTIDO:PHASE:unpack"
'''

# We use a depinst phase here because we don't want to add a Dockerfile to the
# repo where we prepare a build container.
# This is, of course, not be the way it would be done in a real-world scenario!
depinst.script = '''
    echo "#BUTIDO:PHASE:depinst"
    echo "#BUTIDO:PROGRESS:0"
    for n in {1..10}; do sleep 0.1; done
    echo "#BUTIDO:PROGRESS:10"
'''

configure.script = '''
    echo "#BUTIDO:PHASE:configure-preparing"
    for n in {1..10}; do sleep 0.1; done

    echo "#BUTIDO:PROGRESS:20"
    for n in {1..10}; do sleep 0.1; done
'''

build.script = '''
    echo "#BUTIDO:PHASE:build"

    for n in {1..10}; do sleep 0.1; done

    echo "#BUTIDO:PROGRESS:60"
'''

install.script = '''
    echo "#BUTIDO:PHASE:install"
    for n in {1..10}; do sleep 0.1; done

    echo "#BUTIDO:PROGRESS:80"
'''


