name              = "d"
version           = "4"

[sources.src]
url       = "http://localhost:8180/d-4.source"
hash.hash = "e8332116d7a7104f4affc10b6c65a93027441437"

[dependencies]
build = ["i =9"]

[phases]
build.script = '''
    echo "Building {{name}} in version {{version}}"
'''
