name = "j"
version = "10"

[dependencies]
runtime = ["s =19.0", "s =19.1", "s =19.2", "s =19.3", "t =20"]

[sources.src]
url = "https://example.com"
hash.hash = "4143d3a341877154d6e95211464e1df1015b74bd"

