# Configuration file for BUTIDO for this repository

# In the example, these are configured via the environment.
# See README.md
#releases     = "/tmp/example-1-releases"
#staging      = "/tmp/example-1-staging"
#source_cache = "/tmp/example-1-sources"
#log_dir      = "/tmp/example-1-logs"
#database_host     = "localhost"
#database_port     = 5432
#database_user     = "pgdev"
#database_password = "password"
#database_name     = "butido"

script_highlight_theme = "Solarized (dark)"

script_linter = "linterscript"

# Phases which can be configured in the packages
available_phases = [ "checksource", "unpack", "build", "package" ]

[docker]
# Images which can be used to build
# images not listed here are automatically rejected
images = [ "debian:bullseye" ]
verify_images_present = true

# List of docker endpoints
[[docker.endpoints]]
name          = "localhost"
uri           = "http://0.0.0.0:8095"
endpoint_type = "http"
speed         = 1
maxjobs       = 10

[containers]
# environment variables which are allowed during container start
# This way, errors (typos) when passing environment to a build can be prevented
check_env_names = true
allowed_env = [ "FOO", "BAR" ]

