version           = "1"
version_is_semver = false

# no patches by default
patches = []

[sources.src]
hash.type = "sha1"
download_manually = false

[dependencies]
build           = []
runtime         = []

# Root description of phases
# can be overridden as well
[phases]

checksource.script = '''
    {{phase "Checking sources"}}
    {{progress 0}}

    echo "Sources for this Package:"
    {{#each sources}}
    echo "{{@key}} : {{this.url}}"
    echo "{{this.hash.type}}: {{this.hash.hash}}"

    if [ ! -e /inputs/{{@key}}-{{this.hash.hash}}.source ]; then
        {{state "ERR" "Failed to find source" }}
        exit 1
    fi
    {{/each}}
    {{progress 20}}

    echo "All sources:"
    echo "------------"

    ls /inputs

    echo "------------"
'''

unpack.script = '''
    {{phase "Unpacking sources"}}

    mkdir /build
    {{#each sources}}
    mv /inputs/{{@key}}-{{this.hash.hash}}.source /build/
    {{/each}}
    {{progress 40}}

    echo "Moving dependencies to /build"
    mv /inputs/*.pkg /build/
    {{progress 60}}


    ls /build
'''

package.script = '''
    {{phase "package"}}

    mkdir /outputs
    for f in /build/*; do
        cat "$f" | sed 's,^,  ,' >> /outputs/{{name}}-{{version}}.pkg
    done

    {{progress 100}}
    {{state "OK"}}


