name              = "i"
version           = "9"

[sources.src]
url       = "http://localhost:8180/i-9.source"
hash.hash = "11578a82ef30e5c9787f6a2342dec4b856c257d2"

[phases]
build.script = '''
    echo "Building {{name}} in version {{version}}"
'''
