# Configuration file for BUTIDO for this repository

# repository of package definitions
repository = "/tmp/butido_example_1"

# Phases which can be configured in the packages
available_phases = [ "unpack", "build", "install", "package" ]

[docker]
# Images which can be used to build
# images not listed here are automatically rejected
images = [ "debian:bullseye" ]

# List of docker endpoints
[[docker.endpoints]]
name          = "example host name"
uri           = "http://0.0.0.0:8095"
endpoint_type = "http"


[containers]
# environment variables which are allowed during container start
# This way, errors (typos) when passing environment to a build can be prevented
allowed_env = [ "PATH" ]

